# Dependencies
markdown:         Kramdown
highlighter:      pygments
plugins: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            "Help me..."
tagline:          ''
description:      "decide what to write here!"
url:              "https://nsphinc.github.io/"
baseurl:          "https://nsphinc.github.io/"
# baseurl:          /
author:
  name:           'Gabriel Chu'

paginate:         5

# Custom vars
version:          2.7.0

github:
  repo:           https://github.com/nsphinc # replace with my github
