# Dependencies
markdown:         Kramdown
highlighter:      pygments
plugins: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            "Q-Space"
tagline:          ''
description:      Gabriel Chu <br> 4th Year | MEng Oxford
url:              "https://nsphinc.github.io/"
baseurl:          "https://nsphinc.github.io/"
cvurl:            "https://nsphinc.github.io/cv_GabrielChu.pdf"

author:
  name:           'Gabriel Chu'

paginate:         5
paginate_path: "blog/page:num/"

# Custom vars
version:          2.7.0

github:
  repo:           https://github.com/nsphinc
